In [1]:
# code
# https://docs.google.com/document/d/1BX7k8q2X7C32DB2TJFqk5a2CJDg-aUBJTJIVqwo1A4Y/edit

In [2]:
import numpy as np

In [3]:
# wrong values
a = np.sin(30)
b = np.cos(30)
c = np.tan(30)
print(a)
print(b)
print(c)

-0.9880316240928618
0.15425144988758405
-6.4053311966462765


In [4]:
# the correct values came by ==> degree * pi/180
a = np.sin(30*np.pi/180)
b = np.cos(30*np.pi/180)
c = np.tan(30*np.pi/180)

print(a)
print(b)
print(c)

#the same out 
print("\n")
a = np.sin(np.deg2rad(30))
b = np.cos(np.deg2rad(30))
c = np.tan(np.deg2rad(30))
print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896256


0.49999999999999994
0.8660254037844387
0.5773502691896256


In [5]:
a = np.round(3.6873)
print(a)
a = np.round(3.6873,1)
print(a)
a = np.round(3.6873,2)
print(a)
a = np.round(3.6873,3)
print(a)

4.0
3.7
3.69
3.687


In [6]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

b = [[1,2,3]]
print(np.array(b))
print(type(b))


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]]
<class 'list'>


In [7]:
print(np.array([range(i , i + 3) for i in [1,4,7] ]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.empty((3,2)))

[[1.1e-322 0.0e+000]
 [0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000]]


In [9]:
print(np.random.uniform(1,10)) # one number in range 1:10

2.1033958992374906


In [10]:
print(np.random.uniform(1,10,3)) # 3 numbera in range 1:10

[7.92765315 8.32079895 1.19875606]


In [11]:
print(np.random.random((3,2))) # 0:1

[[0.78534552 0.79280689]
 [0.74864746 0.5679696 ]
 [0.79044537 0.03993236]]


In [12]:
print(np.random.random((3,2)) *10) # 1:10

[[8.2459098  8.78214643]
 [2.3937754  7.01735289]
 [3.61371342 9.05152855]]


In [13]:
print(np.random.randint((100))) 
print(np.random.randint(50,100, size = 3))
print(np.random.randint(50,100, (4,4)))

90
[61 74 86]
[[79 78 88 86]
 [65 65 72 60]
 [97 95 81 97]
 [82 58 77 70]]


In [14]:
a = [1,2,3,4,5]
print(a)
np.random.shuffle(a)#random sort
print(a)

[1, 2, 3, 4, 5]
[2, 5, 4, 3, 1]


In [15]:
identityMatrix = np.eye(3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a = np.full((3,2),7)
print(a)

[[7 7]
 [7 7]
 [7 7]]


In [17]:
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [18]:
a = np.linspace(1,51) # defult 50 num
print(a)
print("\n")
a = np.linspace(0,20, 5) # equality distance
print(a)

[ 1.          2.02040816  3.04081633  4.06122449  5.08163265  6.10204082
  7.12244898  8.14285714  9.16326531 10.18367347 11.20408163 12.2244898
 13.24489796 14.26530612 15.28571429 16.30612245 17.32653061 18.34693878
 19.36734694 20.3877551  21.40816327 22.42857143 23.44897959 24.46938776
 25.48979592 26.51020408 27.53061224 28.55102041 29.57142857 30.59183673
 31.6122449  32.63265306 33.65306122 34.67346939 35.69387755 36.71428571
 37.73469388 38.75510204 39.7755102  40.79591837 41.81632653 42.83673469
 43.85714286 44.87755102 45.89795918 46.91836735 47.93877551 48.95918367
 49.97959184 51.        ]


[ 0.  5. 10. 15. 20.]


In [19]:
a = np.random.randint(0,10,(3,3))
print(a)
b = np.count_nonzero(a)
print(b)
c = np.count_nonzero(a > 5)
print(c)
d = np.count_nonzero(a > 5 , axis = 1) # in each row
print(d)
t = np.any(a>4)
print(t)
tt = np.any(a>7 , axis = 1)
print(tt)
al = np.all(a>1)
print(al)

[[9 4 0]
 [2 3 0]
 [3 7 8]]
7
3
[1 0 2]
True
[ True False  True]
False


In [20]:
a = np.random.randint(4,20 , size = 9).reshape(3,3)
b = a > 10
c = a[b]
print(a)
print('-------------------')
print(b)
print('-------------------')
print(c)

[[ 6 19 14]
 [13  4 16]
 [13 11  9]]
-------------------
[[False  True  True]
 [ True False  True]
 [ True  True False]]
-------------------
[19 14 13 16 13 11]


In [21]:
a = np.arange(1,6)
print(a)
print(sum(a))
print(a.sum())
print(np.multiply.reduce(a))
print(np.multiply.outer(a,a))
print(np.add.accumulate(a))
print(np.multiply.accumulate(a))
print(np.ndim(a))

[1 2 3 4 5]
15
15
120
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[ 1  3  6 10 15]
[  1   2   6  24 120]
1


In [22]:
a = np.arange(3,39).reshape(6,6)
print(a)
print(np.linalg.det(a))
print(a[2][2])
print(a[2,2])
print('--------------')
print(a[3:5]) 
print(a[3:5 ,2]) # a[row , col]
print(a[3,1]) # == a [3][1]
print(a[:,1:3]) 
print(a[1:3,:]) 
print(a[2:,3:])
print(a[:2,:3])
print(a[:,:-1])
print(a[-1,:])

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]
 [15 16 17 18 19 20]
 [21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]]
0.0
17
17
--------------
[[21 22 23 24 25 26]
 [27 28 29 30 31 32]]
[23 29]
22
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]
 [34 35]]
[[ 9 10 11 12 13 14]
 [15 16 17 18 19 20]]
[[18 19 20]
 [24 25 26]
 [30 31 32]
 [36 37 38]]
[[ 3  4  5]
 [ 9 10 11]]
[[ 3  4  5  6  7]
 [ 9 10 11 12 13]
 [15 16 17 18 19]
 [21 22 23 24 25]
 [27 28 29 30 31]
 [33 34 35 36 37]]
[33 34 35 36 37 38]


In [23]:
a = np.arange(3,39).reshape(6,6)
print(a)
print('--------------')
print(a[::2,::3])
print(a[::-1,::-1])
print(a[-1::,-1::])

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]
 [15 16 17 18 19 20]
 [21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]]
--------------
[[ 3  6]
 [15 18]
 [27 30]]
[[38 37 36 35 34 33]
 [32 31 30 29 28 27]
 [26 25 24 23 22 21]
 [20 19 18 17 16 15]
 [14 13 12 11 10  9]
 [ 8  7  6  5  4  3]]
[[38]]


In [24]:
x = [1,2,3,4,5,6,7,8]
x1,x2,x3 = np.split(x,(3,6))
print(x1,x2,x3)
x1,x2,x3 = np.split(x,(4,0))
print(x1,x2,x3)

[1 2 3] [4 5 6] [7 8]
[1 2 3 4] [] [1 2 3 4 5 6 7 8]


In [25]:
a = np.arange(4).reshape(2,2)
b = 2*a
print(a)
print('------------')
print(b)
c = np.vstack((a,b)) # v ==> vertical,must a & b have the same col
print('------------')
print(c)
c = np.hstack((a,b)) # h ==> horizontal,must a & b have the same row
print('------------')
print(c)


[[0 1]
 [2 3]]
------------
[[0 2]
 [4 6]]
------------
[[0 1]
 [2 3]
 [0 2]
 [4 6]]
------------
[[0 1 0 2]
 [2 3 4 6]]


In [26]:
a = np.random.randint(5,20,size=9).reshape(3,3)
b = np.random.randint(5,20,size=9).reshape(3,3)
c = np.concatenate((a,b) , axis = 0) # == vstack,horizontal
print(a)
print('------------')
print(b)
print('------V------')
print(c)
c = np.concatenate((a,b) , axis = 1) # == hstack ,horizontal
print('-------H-----')
print(c)

[[14  6 10]
 [17  9 11]
 [15  7 12]]
------------
[[14  8  9]
 [ 8  6 17]
 [ 9 17 16]]
------V------
[[14  6 10]
 [17  9 11]
 [15  7 12]
 [14  8  9]
 [ 8  6 17]
 [ 9 17 16]]
-------H-----
[[14  6 10 14  8  9]
 [17  9 11  8  6 17]
 [15  7 12  9 17 16]]


In [27]:
a = np.random.randint(5,20,size=9).reshape(3,3)
b = np.random.randint(5,20,size=9).reshape(3,3)
print(a+b)

[[29 33 25]
 [14 24 29]
 [28 26 29]]


In [28]:
a = np.random.randint(5,20,size=9).reshape(3,3)
b = np.random.randint(5,20,size=9).reshape(3,3)
print(a*b) # each cell in a * Opposite cell in b 
print(a/b) # each cell in a / Opposite cell in b 

[[144 228 221]
 [ 42 110  90]
 [224 238  78]]
[[0.44444444 1.58333333 0.76470588]
 [0.85714286 0.90909091 0.4       ]
 [1.14285714 1.21428571 2.16666667]]


In [29]:
a = np.random.randint(5,20,size=6).reshape(2,3)
b = np.random.randint(5,20,size=6).reshape(3,2)
print(np.dot(a,b)) # (2*3)(3,2) 
 

[[501 479]
 [356 346]]


In [30]:
a = np.random.randint(1,10 , size = 9).reshape(3,3)
print(a)
print('-------------')
print(np.sum(a))
print(a.sum())
print('-----summation of each row--------')
print(np.sum(a , axis = 1))
print(a.sum(axis = 1))
print('-----summation of each col--------')
print(np.sum(a , axis = 0))
print(a.sum(axis = 0))


[[9 9 9]
 [4 1 9]
 [8 7 3]]
-------------
59
59
-----summation of each row--------
[27 14 18]
[27 14 18]
-----summation of each col--------
[21 17 21]
[21 17 21]


In [31]:
a = np.random.randint(1,10 , size = 9).reshape(3,3)
print(a.mean())
print(a.std())
print(a.var()) # variance 

4.555555555555555
2.629368792488718
6.913580246913581


In [32]:
a = np.random.randint(1,10 , size = 9).reshape(3,3)
print(a)
print('-----sorting of each row--------')
print(np.sort(a,axis = 1))
print('-----sorting of each col--------')
print(np.sort(a,axis = 0))

[[4 4 3]
 [7 5 1]
 [2 1 8]]
-----sorting of each row--------
[[3 4 4]
 [1 5 7]
 [1 2 8]]
-----sorting of each col--------
[[2 1 1]
 [4 4 3]
 [7 5 8]]


In [33]:
matrix_a = np.random.randint(1,4 , size = 9).reshape(3,3)
matrix_b = np.linalg.inv(matrix_a)
identity_M = np.dot(matrix_a, matrix_b)
print(matrix_a)
print('-------------')
print(matrix_b)
print('-------------')
print(identity_M)
# x = 2 , inv = 1/2 , because 2*1/2=1
# matrix a * inverse a = identity matrix 

[[3 2 1]
 [3 1 2]
 [1 3 3]]
-------------
[[ 0.2         0.2        -0.2       ]
 [ 0.46666667 -0.53333333  0.2       ]
 [-0.53333333  0.46666667  0.2       ]]
-------------
[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16 -1.11022302e-16  1.00000000e+00]]


# Polynomial

In [34]:
# Best fit line deg of 1
import numpy as np
Polynomial = np.polynomial.Polynomial
X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])
points,stats = Polynomial.fit(X,Y,1,full=True)
print(points) # Y = 5.5X-4.5

poly([ 5.5 -4.5])


In [35]:
# Best fit line deg of 2
import numpy as np
Polynomial = np.polynomial.Polynomial
X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])
points,stats = Polynomial.fit(X,Y,2,full=True)
print(points) # Y = 5.5X^2 - 4.5X

poly([ 5.50000000e+00 -4.50000000e+00  4.47311763e-16])


In [36]:
# writing equations
import numpy as np
a = np.poly1d((-7))
b = np.poly1d((-7,2))
c = np.poly1d((-7,2,1))
d = np.poly1d((-7,2,1,3))
e = np.poly1d((-7,2,1,3,6))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
-------------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6


In [37]:
equ = np.poly1d((-7,2,1,3,6))
print(equ)
print(equ(0)) # when x = 0
print('--------- the same ----------------')
equ = np.polyval((-7,2,1,3,6) , 0)
print(equ)

    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
6
--------- the same ----------------
6


In [38]:
# derivatives 
equ = np.poly1d((1,2,3))
der1 = np.polyder((a))
der2 = np.polyder((a),2)

print(der1)
print('-----------when X = 2--------------')
print(der1(2))
print('-------------------------')


print(der2)
print('-----------when X = 2--------------')
print(der2(2)) # when X = 2


 
0
-----------when X = 2--------------
0.0
-------------------------
 
0
-----------when X = 2--------------
0.0


In [39]:
# integration
a = np.polyint(np.poly1d((1,2,3)))
b = np.polyint(np.poly1d((1,2,3)),2)
c = np.polyint(np.poly1d((1,2,3)),3)  
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)


        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x


In [40]:
# roots of equationns
# that's numbers make the equation = 0

a = np.roots(np.poly1d((1,2)))
b = np.roots(np.poly1d((1,2,3)))


print(a)
print('-------------------------')
print(b)


[-2.]
-------------------------
[-1.+1.41421356j -1.-1.41421356j]


# dates

In [41]:
date = np.datetime64('2019-08-26')
print(date)
date = date + np.arange(11)
print(date)

2019-08-26
['2019-08-26' '2019-08-27' '2019-08-28' '2019-08-29' '2019-08-30'
 '2019-08-31' '2019-09-01' '2019-09-02' '2019-09-03' '2019-09-04'
 '2019-09-05']


In [42]:
a = np.datetime64('1997-07-21')
b = np.datetime64('2019-08-26')
print(b-a)

8071 days


# lambda

In [43]:
l = (lambda x:x**2)
print(l(7))

49


In [44]:
l = np.fromfunction(lambda x:x**2 , (6,))
print(l)

[ 0.  1.  4.  9. 16. 25.]


In [45]:
x = np.fromfunction(lambda i,j:i+j , (4,5))
print(x)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]


In [46]:
x = np.fromfunction(lambda i,j,k: i+j+k, (2,3,4))
print(x)


[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]
