# 1- from sklearn

In [48]:
import sklearn.externals.joblib as jb
import numpy as np
import pandas as pd
from sklearn.svm import SVR

In [49]:
x = np.random.randint(10,size =20).reshape(4,5)
y = [5,8,9,6]

model = SVR()
model.fit(x,y)


/Users/fox/anaconda3/envs/newEnv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [50]:
# saving file
jb.dump(model, 'save file.sav')

['save file.sav']

### if i restart kernal and run this command , will get error
* model.predict([[2,3,6,5,9]])


In [51]:
# So, for load the previous data that recorded
model_saved = jb.load('save file.sav')
model_saved.predict([[2,3,6,5,9]])

array([6.9978533])

# 2- from pickle

In [52]:
import pickle as pk

In [53]:

x = np.random.randint(10,size =20).reshape(4,5)
y = [5,8,9,6]


model = SVR()
model.fit(x,y)



/Users/fox/anaconda3/envs/newEnv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [54]:
pk.dump(model , open('saved file2.sav','wb'))

model.predict([[2,3,6,5,9]])


array([6.94147996])

In [55]:
savedmodel = pk.load(open('saved file2.sav','rb'))
savedmodel.predict([[2,3,6,5,9]])


array([6.94147996])