In [70]:
# import numpy as np
# from scipy.io import loadmat


# data = loadmat('D:\\z\\1\\ex3data1.mat')

# print(data) 
# print(data['X']) 
# print(data['y'])
# print('X Shape = ' ,  data['X'].shape) 
# print('Y Shape = ', data['y'].shape)

# print(data['X'][0]) 
# print(data['X'][0][155]) 
# print('===================================================')





# def sigmoid(z):
#     return 1 / (1 + np.exp(-z))

# def cost(theta, X, y, learningRate):
#     theta = np.matrix(theta)
#     X = np.matrix(X)
#     y = np.matrix(y)
#     first = np.multiply(-y, np.log(sigmoid(X * theta.T)))
#     second = np.multiply((1 - y), np.log(1 - sigmoid(X * theta.T)))
#     reg = (learningRate / 2 * len(X)) * np.sum(np.power(theta[:,1:theta.shape[1]], 2))
#     return np.sum(first - second) / (len(X)) + reg


# def gradient_with_loop(theta, X, y, learningRate):
#     theta = np.matrix(theta)
#     X = np.matrix(X)
#     y = np.matrix(y)
    
#     parameters = int(theta.ravel().shape[1])
#     grad = np.zeros(parameters)
    
#     error = sigmoid(X * theta.T) - y
    
#     for i in range(parameters):
#         term = np.multiply(error, X[:,i])
        
#         if (i == 0):
#             grad[i] = np.sum(term) / len(X)
#         else:
#             grad[i] = (np.sum(term) / len(X)) + ((learningRate / len(X)) * theta[:,i])
    
#     return grad

# def gradient(theta, X, y, learningRate):
#     theta = np.matrix(theta)
#     X = np.matrix(X)
#     y = np.matrix(y)
    
#     parameters = int(theta.ravel().shape[1])
#     error = sigmoid(X * theta.T) - y
    
#     grad = ((X.T * error) / len(X)).T + ((learningRate / len(X)) * theta)
    
#     # intercept gradient is not regularized
#     grad[0, 0] = np.sum(np.multiply(error, X[:,0])) / len(X)
    
#     return np.array(grad).ravel()

# from scipy.optimize import minimize

# def one_vs_all(X, y, num_labels, learning_rate):
#     rows = X.shape[0] #5000
#     params = X.shape[1] #400
    
#     # k X (n + 1) array for the parameters of each of the k classifiers
#     all_theta = np.zeros((num_labels, params + 1))
    
#     print('all_theta shape ' , all_theta.shape)
#     # insert a column of ones at the beginning for the intercept term
#     X = np.insert(X, 0, values=np.ones(rows), axis=1)
#     print('X shape ' , X.shape)
    
#     # labels are 1-indexed instead of 0-indexed
#     for i in range(1, num_labels + 1):
#         theta = np.zeros(params + 1)
#         y_i = np.array([1 if label == i else 0 for label in y])
#         y_i = np.reshape(y_i, (rows, 1))
        
#         # minimize the objective function
#         fmin = minimize(fun=cost, x0=theta, args=(X, y_i, learning_rate), method='TNC', jac=gradient)
#         all_theta[i-1,:] = fmin.x
    
#     return all_theta



# rows = data['X'].shape[0]
# params = data['X'].shape[1]

# print('rows = ' ,rows)
# print('params = ' , params)

# print('===================================================')


# all_theta = np.zeros((10, params + 1))

# print('all_theta \n' , all_theta)
# print('all_theta shape \n' , all_theta.shape)

# print('===================================================')


# X = np.insert(data['X'], 0, values=np.ones(rows), axis=1)


# print(X) 
# print('X Shape = ' ,  X.shape) 

# print('===================================================')

# theta = np.zeros(params + 1)

# print('theta \n' , theta ) 

# print('===================================================')


# y_0 = np.array([1 if label == 0 else 0 for label in data['y']])

# print('y_0')
# print(y_0.shape)
# print(y_0)

# print('===================================================')

# y_0 = np.reshape(y_0, (rows, 1))


# print('y_0')
# print(y_0.shape)
# print(y_0)

# print('===================================================')

# print()
# print('X.shape = ',X.shape)
# print()
# print('y.shape = ',y_0.shape)
# print()
# print('theta.shape = ',theta.shape)
# print()
# print('all_theta.shape = ',all_theta.shape)

# print()
# print('data array = ' , np.unique(data['y']))

# print()




# all_theta = one_vs_all(data['X'], data['y'], 1, 1)

# print('Theta shape =   ' , all_theta.shape)
# print('Theta = ')
# print(all_theta)



# def predict_all(X, all_theta):
#     rows = X.shape[0]
#     params = X.shape[1]
#     num_labels = all_theta.shape[0]
    
#     # same as before, insert ones to match the shape
#     X = np.insert(X, 0, values=np.ones(rows), axis=1)
    
#     # convert to matrices
#     X = np.matrix(X)
#     all_theta = np.matrix(all_theta)
    
#     # compute the class probability for each class on each training instance
#     h = sigmoid(X * all_theta.T)
    
#     # create array of the index with the maximum probability
#     h_argmax = np.argmax(h, axis=1)
    
#     # because our array was zero-indexed we need to add one for the true label prediction
#     h_argmax = h_argmax + 1
    
#     return h_argmax

# y_pred = predict_all(data['X'], all_theta)
# correct = [1 if a == b else 0 for (a, b) in zip(y_pred, data['y'])]
# accuracy = (sum(map(int, correct)) / float(len(correct)))
# print ('accuracy = {0}%'.format(accuracy * 100))


In [71]:
import numpy as np
from scipy.io import loadmat


In [72]:
path = '/Users/fox/Desktop/ML_Art/Classification_code/data3.mat'
data = loadmat(path)
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [73]:
data['X'].shape

(5000, 400)

In [74]:
data['y'].shape

(5000, 1)

In [75]:
data['X'][0] # 400 feature for the 1st one

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [76]:
data['X'][0,156] # data['X'][0][156]

1.0474834563069852

In [77]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def cost(theta, X, y, lr):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    
    first_term  = np.multiply(y, np.log(sigmoid(X * theta.T)))
    second_term = np.multiply((1 - y) , np.log(1 - sigmoid(X * theta.T)) )
    summation_term = np.sum(first_term+second_term) / len(X)

    reg = (lr / 2 * len(X)) * np.sum(np.power(theta[: , 1:theta.shape[1]] ,2))
    # theta[: , 1:theta.shape[1]] ==> start form 2nd theta for end of it
    return -1 * summation_term + reg 


def gradientReg(theta, X, y, learningRate):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    
    parameters = int(theta.ravel().shape[1])
    grad = np.zeros(parameters)
    
    error = sigmoid(X * theta.T) - y
    
    for i in range(parameters):
        term = np.multiply(error, X[:,i])
        
        if (i == 0):
            grad[i] = np.sum(term) / len(X)
        else:
            grad[i] = (np.sum(term) / len(X)) + ((learningRate / len(X)) * theta[:,i])
    
    return grad


def gradient(theta, X, y, learningRate):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    
    parameters = int(theta.ravel().shape[1])
    error = sigmoid(X * theta.T) - y
    
    grad = ((X.T * error) / len(X)).T + ((learningRate / len(X)) * theta)
    
    # intercept gradient is not regularized
    grad[0, 0] = np.sum(np.multiply(error, X[:,0])) / len(X)
    
    return np.array(grad).ravel()

from scipy.optimize import minimize

def one_vs_all(X, y, num_labels, learning_rate):
    rows = X.shape[0] #5000
    params = X.shape[1] #400
    
    # k X (n + 1) array for the parameters of each of the k classifiers
    all_theta = np.zeros((num_labels, params + 1))
    
    print('all_theta shape ' , all_theta.shape)
    # insert a column of ones at the beginning for the intercept term
    X = np.insert(X, 0, values=np.ones(rows), axis=1)
    print('X shape ' , X.shape)
    
    # labels are 1-indexed instead of 0-indexed
    for i in range(1, num_labels + 1):
        theta = np.zeros(params + 1)
        y_i = np.array([1 if label == i else 0 for label in y])
        y_i = np.reshape(y_i, (rows, 1))
        
        # minimize the objective function
        fmin = minimize(fun=cost, x0=theta, args=(X, y_i, learning_rate), method='TNC', jac=gradient)
        all_theta[i-1,:] = fmin.x
    
    return all_theta

In [78]:
rows = data['X'].shape[0]
params= data['X'].shape[1]
print(rows)
print(params)

5000
400


In [79]:
all_thetas = np.zeros((10, params+1))
all_thetas.shape

(10, 401)

In [80]:
X = np.insert(data['X'], 0, values=np.ones(rows), axis=1)
print(X)
print(X.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(5000, 401)


In [81]:
theta = np.zeros(params+1)
theta[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
y_0 = np.array([1 if v == 0 else 0 for v in data['y']])
print(y_0[:10] )
print(y_0.shape)

[0 0 0 0 0 0 0 0 0 0]
(5000,)


In [83]:
y_0 = np.reshape(y_0, (rows,1))
y_0.shape

(5000, 1)

In [84]:
print('X.shape = ',X.shape)
print('y.shape = ',y_0.shape)
print('theta.shape = ',theta.shape)
print('all_theta.shape = ',all_thetas.shape)
print('data array = ' , np.unique(data['y']))

X.shape =  (5000, 401)
y.shape =  (5000, 1)
theta.shape =  (401,)
all_theta.shape =  (10, 401)
data array =  [ 1  2  3  4  5  6  7  8  9 10]


In [85]:
# def one_vs_all(X, y, num_labels, lr):
#     rows = X.shape[0]
#     params = X.shape[1]
#     all_theta = np.zeros((num_labels, params+1))
#     print('all theta shape' , all_theta.shape)
#     X = np.insert(X, 0, values=np.ones(rows), axis=1)
#     print('X shape' , X.shapee)
    

    

## Processing

In [86]:
all_thetas = one_vs_all(data['X'], data['y'], 1, 1) 
print('Theta shape' , all_thetas)
print('Theta =\n' , theta)
                        

all_theta shape  (1, 401)
X shape  (5000, 401)
Theta shape [[-3.70247931e-05  0.00000000e+00  0.00000000e+00  1.45740955e-10
  -1.26000447e-09 -1.07067738e-09 -2.29267664e-08 -2.08810303e-08
  -2.32625634e-11 -1.77197005e-08 -1.42717370e-08 -3.33472943e-09
   2.45288427e-09  4.29598310e-09  6.83398814e-09  9.29087981e-09
   5.08966529e-09  1.40383167e-09  4.28809828e-11 -1.79446409e-11
   0.00000000e+00 -1.99645441e-12  2.16948409e-11 -1.85206014e-09
   1.74264636e-08  2.23711392e-08 -5.02669568e-08 -1.41936268e-07
  -2.11236024e-07 -2.07880612e-07 -1.09764260e-07 -8.71206075e-09
   1.24087889e-08 -3.78652021e-09 -1.69654969e-08 -4.16799824e-08
  -1.74641877e-08  1.74915642e-09  6.56556694e-09  1.60534527e-09
   5.57721634e-10  1.48933217e-11 -3.36720615e-10  6.07719583e-10
   2.75179854e-08 -4.77049315e-08 -5.16705706e-07 -9.73763760e-07
  -1.19167516e-06 -9.55309557e-07 -5.09174904e-07 -3.56951542e-07
  -2.88959050e-07 -3.74443703e-07 -7.49724899e-07 -8.72934691e-07
  -4.58384972e-07

In [87]:
all_thetas = one_vs_all(data['X'], data['y'], 10, 1) 
print('Theta shape' , all_thetas)
print('Theta =\n' , theta)
                        

all_theta shape  (10, 401)
X shape  (5000, 401)
Theta shape [[-3.70247931e-05  0.00000000e+00  0.00000000e+00 ... -2.24803602e-10
   2.31962907e-11  0.00000000e+00]
 [-8.96250716e-05  0.00000000e+00  0.00000000e+00 ...  7.26120810e-09
  -6.19965284e-10  0.00000000e+00]
 [-8.39553387e-05  0.00000000e+00  0.00000000e+00 ... -7.61695633e-10
   4.64917656e-11  0.00000000e+00]
 ...
 [-7.00832439e-05  0.00000000e+00  0.00000000e+00 ... -6.92009029e-10
   4.29241494e-11  0.00000000e+00]
 [-7.65187941e-05  0.00000000e+00  0.00000000e+00 ... -8.09503274e-10
   5.31058721e-11  0.00000000e+00]
 [-6.63412747e-05  0.00000000e+00  0.00000000e+00 ... -3.49766172e-09
   1.13668635e-10  0.00000000e+00]]
Theta =
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.

In [88]:
def predict_all(X, all_theta):
    rows = X.shape[0]
    params = X.shape[1]
    num_labels = all_theta.shape[0]
    
    # same as before, insert ones to match the shape
    X = np.insert(X, 0, values=np.ones(rows), axis=1)
    
    # convert to matrices
    X = np.matrix(X)
    all_theta = np.matrix(all_theta)
    
    # compute the class probability for each class on each training instance
    h = sigmoid(X * all_theta.T)
    
    # create array of the index with the maximum probability
    h_argmax = np.argmax(h, axis=1)
    
    # because our array was zero-indexed we need to add one for the true label prediction
    h_argmax = h_argmax + 1
    
    return h_argmax


In [90]:
y_pred = predict_all(data['X'], all_thetas)
correct = [1 if a == b else 0 for (a, b) in zip(y_pred, data['y'])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))

accuracy = 74.6%
